default:
  image: ubuntu:latest
  cache:
    paths:
      - ~/.cache/pip
  
  before_script:
    - apt-get update -y
    - apt-get install -y python3-pip
    - pip3 install --upgrade pip
    - pip3 install -r requirements.txt
    - mv .env.example .env

django-tests:
  stage: test
  services:
    - postgres:alpine
  script:
    - coverage run --source='.' manage.py test
    - coverage xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    expire_in: 1 week
